version: "3.8"

services:
  mcp-server:
    container_name: shadcn-ui-mcp-server
    image: ghcr.io/mamba-mental/shadcn-ui-mcp-server:latest
    ports:
      - "7707:3000"  # Changed from 7070:3000
    volumes:
      - /volume1/docker/stacks/shadcn-ui-mcp-server/data:/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
