version: "3.8"

services:
  mcp-server:
    container_name: shadcn-ui-mcp-server
    image: ghcr.io/ymadd/shadcn-ui-mcp-server:latest
    ports:
      - "7070:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
